# Note: Some of the parameters are overridden in the launch file
frame_robot              : base_link
path                     : hsas_local/sPath
odom                     : odom
cmd_vel                  : hsas_local/cmd_vel
hz                       : 50.0
look_forward             : 0.5
curv_forward             : 0.5
k_dist                   : 1.0
k_ang                    : 1.0
k_avel                   : 1.0
k_dcel                   : 1.0
dist_lim                 : 0.5
dist_stop                : 0.3
rotate_ang               : 0.785398
max_vel                  : 1.0
max_angvel               : 1.0
max_acc                  : 1.0
max_angacc               : 2.0
path_step                : 2
distance_angle_factor    : 0.0
switchback_dist          : 0.3
goal_tolerance_dist      : 0.5
goal_tolerance_ang       : 0.087266
stop_tolerance_dist      : 0.1
stop_tolerance_ang       : 0.05
no_position_control_dist : 0.0
min_tracking_path        : noPosCntlDist
allow_backward           : false
limit_vel_by_avel        : true
check_old_path           : false
