footprint: [[0, -0.125], [0, 0.125], [-0.176, 0.125], [-0.176, -0.125]]
footprint_padding: 0.05

robot_base_frame: base_link
update_frequency: 5.0
publish_frequency: 5.0
transform_tolerance: 0.5

resolution: 0.20

obstacle_range: 15.0
raytrace_range: 8.0

  #layer definitions
static:
  map_topic: /map
  subscribe_to_updates: true

obstacles_laser:
  observation_sources: laser
  laser: {data_type: LaserScan, clearing: true, marking: true, topic: scan, inf_is_valid: true}

inflation:
  inflation_radius: 2.0

